### ISSUE TITLE
Game breaking mod with most recent update (Bog Witch)

### ISSUE THREAD

**Issue by DrexXxor** [sirskunkalot/PlanBuild#101]
all menu items gain $ symbol and BETA badge appears in bottom right instead of mod warning

**Comment by DrexXxor** [comment]
![Image3](https://github.com/user-attachments/assets/4ec5fc05-fb51-4e09-9889-d723d1e2741a)
![Image4](https://github.com/user-attachments/assets/96ec1665-f8fe-47f6-98ef-a3890d2dd653)

**Comment by iamthe-fixer** [comment]
There was a jotunn update that corrected the main menu issue, however PlanBuild is non functional, a lot of red code when it tries to load.

**Comment by Ultimate-Fluff** [comment]
> There was a jotunn update that corrected the main menu issue, however PlanBuild is non functional, a lot of red code when it tries to load.

I submitted an error report in the latest Issue. You can actually make plans and build with planbuild, but the selection tool is completely non-functional.

**Comment by iamthe-fixer** [comment]
All the lines beginning with [info are white the rest are red in the commands window


[Warning:  HarmonyX] AccessTools.DeclaredMethod: Could not find method for type ItemDrop+ItemData and name GetTooltip and parameters (ItemDrop+ItemData, int, bool, float)
[Error  : Unity Log] ArgumentException: Undefined target method for patch method static void TeleportEverything.Plugin+GetTooltip_Patch::Postfix(ItemDrop+ItemData item, String& __result)
Stack trace:
HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
Rethrow as HarmonyException: Patching exception in method null
HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.<PatchAll>b__11_0 (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.PatchAll () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
TeleportEverything.Plugin.Awake () (at <4dade203ff8547c4bf997053f3791d4b>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.GameObject:.cctor()
PlatformTools.Common.SingletonMonoBehaviour`1:get_Instance()
PlatformTools.PlatformManagerInitializer:OnRuntimeMethodLoad()

[Info   :   BepInEx] Loading [PlanBuild 0.17.0]
[Info   :Jotunn.Main] Initializing InputManager
[Info   :Jotunn.Main] Initializing GUIManager
[Info   :Jotunn.Main] Initializing MockManager
[Info   :Jotunn.Main] Initializing PieceManager
[Info   :Jotunn.Main] Initializing PrefabManager
[Info   :Jotunn.Main] Initializing AssetManager
[Info   :Jotunn.Main] Initializing LocalizationManager
[Info   :Jotunn.Main] Initializing ItemManager
[Info   :PlanBuild.Blueprints.BlueprintManager] Initializing BlueprintManager
[Info   :Jotunn.Main] Initializing CommandManager
[Info   :PlanBuild.Blueprints.BlueprintSync] Loading known blueprints
[Info   :Jotunn.Main] Initializing UndoManager
[Info   :Jotunn.Main] Initializing KitbashManager
[Info   :PlanBuild.Plans.PlanManager] Initializing PlanManager
[Error  : Unity Log] InvalidOperationException: Parameter #0 of hook for Void Destroy(HitData, Boolean) doesn't match, must be WearNTear or related
Stack trace:
MonoMod.RuntimeDetour.Hook..ctor (System.Reflection.MethodBase from, System.Reflection.MethodInfo to, System.Object target, MonoMod.RuntimeDetour.HookConfig& config) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.Hook..ctor (System.Reflection.MethodBase from, System.Reflection.MethodInfo to, System.Object target, MonoMod.RuntimeDetour.HookConfig config) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.Hook..ctor (System.Reflection.MethodBase from, System.Reflection.MethodInfo to, System.Object target) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.Hook..ctor (System.Reflection.MethodBase method, System.Delegate to) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.HookGen.HookEndpoint._NewHook (System.Reflection.MethodBase from, System.Delegate to) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.HookGen.HookEndpoint._Add[TDelegate] (System.Func`3[T1,T2,TResult] gen, TDelegate hookDelegate) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.HookGen.HookEndpoint.Add (System.Delegate hookDelegate) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Add (System.Reflection.MethodBase method, System.Delegate hookDelegate) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Add[T] (System.Reflection.MethodBase method, System.Delegate hookDelegate) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
On.WearNTear.add_Destroy (On.WearNTear+hook_Destroy ) (at <60548e88939d48598c64a6b671ede244>:0)
PlanBuild.Plans.PlanManager.Init () (at <69f90b2d72e445e98c4e8811c02818b3>:0)
PlanBuild.PlanBuildPlugin.Awake () (at <69f90b2d72e445e98c4e8811c02818b3>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.GameObject:.cctor()
PlatformTools.Common.SingletonMonoBehaviour`1:get_Instance()
PlatformTools.PlatformManagerInitializer:OnRuntimeMethodLoad()

**Comment by iamthe-fixer** [comment]
I was able to place a blueprint in the game, however when i logged out and later returned to the game the house was gone.

**Comment by Nazgul101** [comment]
> I was able to place a blueprint in the game, however when i logged out and later returned to the game the house was gone.

I just placed a blueprint, all pieces are visible but I can walk right through them.

**Comment by lgbtqPP** [comment]
Same problem with walk through pieces.
