### ISSUE TITLE
Language localisation

### ISSUE THREAD

**Issue by Dominowood371** [sirskunkalot/PlanBuild#2]
Сontent without Language localisation.
![Снимок экрана (643)](https://user-images.githubusercontent.com/85061444/129478546-22292dca-c2cb-4f45-9e12-91bafd740bb4.png)
![Снимок экрана (645)](https://user-images.githubusercontent.com/85061444/129478549-7be427bf-7e17-4692-864c-297453be8764.png)
![Снимок экрана (646)](https://user-images.githubusercontent.com/85061444/129478550-0dafffc2-c7e3-428e-b3b8-996769c9089e.png)
![Снимок экрана (647)](https://user-images.githubusercontent.com/85061444/129478553-22df2691-75e2-4398-ac0e-f68ff2c39990.png)
![Снимок экрана (648)](https://user-images.githubusercontent.com/85061444/129478554-7fc97df7-7b26-4afa-be05-2248e67bc080.png)
![Снимок экрана (649)](https://user-images.githubusercontent.com/85061444/129478556-1ed60e5a-2259-4967-b5f6-511efe06a548.png)
![Снимок экрана (650)](https://user-images.githubusercontent.com/85061444/129478558-00b8ae1e-42c8-448a-a0d2-6a648d4296d6.png)

**Comment by sirskunkalot** [comment]
@Dominowood371 Most of the GUI stuff can now be translated. If you want to add Russian translation before release, please do so with the current master
