### ISSUE TITLE
Cannot Place Blueprints

### ISSUE THREAD

**Issue by BrandonT80** [sirskunkalot/PlanBuild#28]
After hours of testing, nobody can place blueprints as a plan. Only direct placement as an admin works.

**Comment by BrandonT80** [comment]
Problem was found that the blueprints take invalid objects, then deletes them on placement, but it is deleted before running the place code and thus tries to place a null object resulting in a null exception.

**Comment by sirskunkalot** [comment]
fixed in 0.8.5
