### ISSUE TITLE
Question: Explain .blueprint format

### ISSUE THREAD

**Issue by himpich** [sirskunkalot/PlanBuild#35]
I would like to make small changes to one of my .blueprint files in order to align some pieces which I am not able to do while building.

Could you please give a short explaination of the fileformat?
something like
```
#SnapPoints:
X;Y;Z
#Pieces
piece_name;Hammerbuildtabname;X;Y;Z;rotation;a;b;c
```
And: are the numbers relative to the "center marker"?

Thanks in advance

**Comment by sirskunkalot** [comment]
I created a wiki page and explained the format a bit. https://github.com/sirskunkalot/PlanBuild/wiki/Blueprint-File-Format

**Comment by sirskunkalot** [comment]
Closing this for now, if you have further question just comment again.
