### ISSUE TITLE
Req: Delete all connected

### ISSUE THREAD

**Issue by luxzg** [sirskunkalot/PlanBuild#37]
When trying and testing I am severely missing "delete all connected pieces" as option in delete tool. For planned pieces it works by just deleting blueprint, but for deleting already built pieces you can only delete by using circle/range tool, which isn't perfect, because it can grab other stuff by accident (specially if you don't want to delete stuff like nearby trees, or smaller nearby buildings).

To explain, I have a 4 floor building set about 30 meters high on trees, and another 30m tower on top of all that, so deleting it all takes a lot of time, specially if you don't want to delete the trees. And there's no other way to make a perfect self-building plan+totem except continued trial and failure :)

I guess it could work same as "select connected", or even if needed make it select then delete, idk.

Thanks for considering!

**Comment by sirskunkalot** [comment]
That should be doable since the "find connected pieces" code is already there. Gonna look into it.

**Comment by sirskunkalot** [comment]
A bit late but with the 0.10.x release you can make a manual selection (supports "connected") and delete those selected pieces.
