### ISSUE TITLE
Blueprint not supported

### ISSUE THREAD

**Issue by Thewraith01** [sirskunkalot/PlanBuild#39]
my blueprint is "not supported" when placed, cannot build any of the parts, tried different terrain
![Nekk_centered](https://user-images.githubusercontent.com/78445502/152737850-1592203d-608d-4b53-9985-de86b6426cf5.png)

**Comment by elonmir** [comment]
Have you checked the log window of BepinEx? Do you get something similar like https://user-images.githubusercontent.com/1140767/154841894-f7531272-eb37-4da0-ba3e-09889be03e3f.png?
