### ISSUE TITLE
Language localisation.

### ISSUE THREAD

**Issue by Dominowood371** [sirskunkalot/PlanBuild#4]
Сontent without Language localisation.

**Open Blueprint Marketplace**

![Снимок экрана (667)](https://user-images.githubusercontent.com/85061444/130322915-d90a7501-9935-4f25-8ab5-43106eef1ab3.png)
![Снимок экрана (668)](https://user-images.githubusercontent.com/85061444/130322916-d989f371-eac7-4320-90dd-7fa57bb6e09a.png)

**Pieces** 
![Снимок экрана (666)](https://user-images.githubusercontent.com/85061444/130323001-8b1dfc38-fedc-48b0-ab01-828d1025954d.png)

**Сontainer**

![Снимок экрана (661)](https://user-images.githubusercontent.com/85061444/130323033-f8d38d59-37e2-4a72-9c9b-7ac9d69e23c8.png)

**Open**

**Missing crafting stations:**

**connected plans ( supported)**

**Required materials:**

![Снимок экрана (665)](https://user-images.githubusercontent.com/85061444/130323039-15c4a7e6-6589-4b41-aebd-19331ebc62f4.png)

When Saving, Transferring, Deleting a Blueprint: **Local, Server**

![Снимок экрана (660)](https://user-images.githubusercontent.com/85061444/130323141-f376283d-24c5-4356-b74b-189e73bedc50.png)

Сategories: **Tools, Blueprint**

![Снимок экрана (656)](https://user-images.githubusercontent.com/85061444/130323357-8eb2037c-4d07-47d8-8573-8d0ea32de3c0.png)

**Comment by Dominowood371** [comment]
I also noticed that there is no visual and sound effect when building and destroying the Plan Totem.

**Comment by sirskunkalot** [comment]
closed with #6
