### ISSUE TITLE
Issues with references

### ISSUE THREAD

**Issue by elonmir** [sirskunkalot/PlanBuild#40]
![image](https://user-images.githubusercontent.com/1140767/154841894-f7531272-eb37-4da0-ba3e-09889be03e3f.png)

**Comment by elonmir** [comment]
It's possible to direct build, but planned build is not possible.

**Comment by elonmir** [comment]
Ok, it seems manually deleting the entries of the items from the build file, seems to fix the issue.

**Comment by sirskunkalot** [comment]
It's because bushes, etc can't be build as a plan. It's a caught exception, though (thus it's a warning) ;) Otherwise it would stop building any other piece on that blueprint.

**Comment by elonmir** [comment]
Ok, maybe I explained a little poorly. I can directly build, with such a plan, but I can not just plan it. The building simply does not get set. After removing the dandelions, it worked like a charm.

**Comment by sirskunkalot** [comment]
Can you provide your .blueprint file? I'll try to recreate the issue then.

**Comment by elonmir** [comment]
![Elonmir_Debug](https://user-images.githubusercontent.com/1140767/155332316-ee0731be-c7c5-4c9d-933a-a8b0f20dafc8.png)
https://gist.githubusercontent.com/elonmir/ec1130047a3e7cabd849fe0e756e1d07/raw/07f3f4cb5be71ec01880734045918ca1c0d6c787/Elonmir_Debug.blueprint

Here you go, can't upload directly, due file extension.

**Comment by sirskunkalot** [comment]
Hey, I think I found the culprit. Fixed it on the current "planhammer" branch. I might need to get this over to the master, but the current revamp on that branch is kind of huge. And I am on vacation for another two weeks or so. So, long story short, willfix - might take some time ;)

**Comment by elonmir** [comment]
Great I could contribute, even if  not codewise... :D

**Comment by sirskunkalot** [comment]
Alright, I am back and this problem should be fixed with the version 0.9.5, out on nexus and thunder (and here on git ofc)

**Comment by elonmir** [comment]
Awesome!
