### ISSUE TITLE
Blueprint format breaks when signs have new lines

### ISSUE THREAD

**Issue by heinermann** [sirskunkalot/PlanBuild#42]
I saved a workshop/storage build which had signs that had newline characters pasted into it from my clipboard. Planbuild saved the file with the following verbatim:

```
wood_beam;Building;15.86383;2.24675;23.53613;0;0.7071067;0;0.7071068;
sign;Furniture;16.10837;2.261719;19.10345;0;0.7071067;0;0.7071068;Drops
Cores
sign;Furniture;16.10837;2.263016;20.05064;0;0.7071067;0;0.7071068;Wood
sign;Furniture;16.10837;2.268932;23.15164;0;0.7071067;0;0.7071068;Equipment                                  
Arrows
sign;Furniture;16.10837;2.271332;18.12659;0;0.7071067;0;0.7071068;Bones
Skins
piece_walltorch;Furniture;16.67725;2.283806;16.65331;0;0;0;1;
sign;Furniture;16.10837;2.286621;22.18644;0;0.7071067;0;0.7071068;Metal
sign;Furniture;16.10837;2.287022;21.3139;0;0.7071067;0;0.7071068;Rocks
Stone
sign;Furniture;16.10837;2.288212;17.20294;0;0.7071067;0;0.7071068;Eyes
Resin
sign;Furniture;13.82892;2.289898;21.19217;0;0.7071068;0;-0.7071068;Rocks
Stone
sign;Furniture;13.80969;2.29834;18.04819;0;0.7071049;0;-0.7071086;Bones
Skins
sign;Furniture;13.80969;2.306366;17.0921;0;0.7071039;0;-0.7071096;Eyes
Resin
piece_walltorch;Furniture;16.67722;2.308266;20.63902;0;0;0;1;
sign;Furniture;13.82892;2.312489;22.18105;0;0.7071068;0;-0.7071068;Metal
sign;Furniture;13.80969;2.321262;20.03839;0;0.7071068;0;-0.7071068;Wood
sign;Furniture;13.80969;2.325722;19.02773;0;0.7071059;0;-0.7071076;Drops
Cores
sign;Furniture;13.8045;2.333824;23.08018;0;0.7071068;0;-0.7071068;Equipment
Arrows
piece_walltorch;Furniture;13.3226;2.335026;16.63385;0;1;0;-1.629207E-07;
```

this leads to the following log message when the game is next loaded
```
[Warning:PlanBuild.Blueprints.Marketplace.BlueprintSync] Could not load blueprint .\BepInEx\config\TheRuins\VanGaymersServer\Laketown\meadows\Planbuild_Laketown_Workshop.blueprint: System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at PlanBuild.Blueprints.PieceEntry.FromBlueprint (System.String line) [0x0002d] in <bd12d75e88ca424faf366223fd1f1e44>:0
  at PlanBuild.Blueprints.Blueprint.FromArray (System.String id, System.String[] lines, PlanBuild.Blueprints.Blueprint+Format format) [0x001be] in <bd12d75e88ca424faf366223fd1f1e44>:0
  at PlanBuild.Blueprints.Blueprint.FromFile (System.String fileLocation) [0x0006c] in <bd12d75e88ca424faf366223fd1f1e44>:0
  at PlanBuild.Blueprints.Marketplace.BlueprintSync.GetLocalBlueprints () [0x000b7] in <bd12d75e88ca424faf366223fd1f1e44>:0
```

This formatting also breaks other mods that may use `.blueprint` files (as in one I am currently developing). I think it should escape newlines when saving.

## Version
- PlanBuild-0.9.5
- Valheim 0.207.20

## Other mods
- Jotunn
- MMHOOK

## Steps to reproduce
1. Place a sign.
2. Edit the sign and paste the following text:

       This
       has
       newlines
3. Save the sign with PlanBuild to a `.blueprint` file.

<img width="225" alt="2022-03-26 21_38_26-Valheim" src="https://user-images.githubusercontent.com/1966366/160266973-3d70ed2d-7463-4f82-bb30-db663cdc74bb.png">

It ~~should~~ shouldn't but does produce the following file:

```
#Name:blueprint087
#Creator:Planbuild
#Description:""
#Category:Blueprints
#Pieces
sign;Furniture;0;0;0;0;0.9807853;0;-0.1950903;This
has
newlines
```

**Comment by sirskunkalot** [comment]
Jees, thanks for pointing that out. willfix

**Comment by sirskunkalot** [comment]
I wonder how you made those newline-signs. That has to be some mod? Anyway, I implemented JSON-serialization for the additionalText column of the CSV now. If you are going to interpret the .blueprint format you should be aware of that, since it adds quotation marks to it now (and escapes newlines with \r\n and stuff).

Closing this as its in the current dev.

**Comment by sirskunkalot** [comment]
PS: if you are using Jötunn for your mod, you can use SimpleJSON to deserialize the field, as we ship it with Jötunn: `additionalInfo = SimpleJson.SimpleJson.DeserializeObject<string>(additionalInfo);`

**Comment by heinermann** [comment]
> I wonder how you made those newline-signs. That has to be some mod?

Just copy(CTRL+C) paste(CTRL+V), should work in vanilla unless they changed it since the issue was created.
