### ISSUE TITLE
Suggestion: Allow planed pieces to be filled with "no placement costs"

### ISSUE THREAD

**Issue by himpich** [sirskunkalot/PlanBuild#44]
If I build something in creative mode, I activate "no placement costs" (debugmode -> b).

In order to fill planned pieces, I still need the mats in my inventory (or nearby containers using mods). I would love to be able to "fill planned pieces" without costs, if the option is enabled (due to debugmode)

This would easily allow to place planned blueprints, work on the support (floor, maybe some iron things) and then build the pieces.

Thanks in advance

**Comment by sirskunkalot** [comment]
Good idea, I will include that in the revamp version (which is to be released soon™)

**Comment by sirskunkalot** [comment]
going to close the issue to keep track of what is implemented in dev ;)
