### ISSUE TITLE
Version 0.5.1	

### ISSUE THREAD

**Issue by Dominowood371** [sirskunkalot/PlanBuild#5]
after update 0.5.1, the text translation for the Blueprint Rune menu was lost, if you go back to version 0.5.0 everything works fine

![Снимок экрана (38)](https://user-images.githubusercontent.com/85061444/132129362-2a4aa155-23f6-403e-a1d2-a48895fe7c21.png)

**Comment by Dominowood371** [comment]
if delete the file Plan Build.english.json and leave the file Plan Build.russian.json

![Снимок экрана (39)](https://user-images.githubusercontent.com/85061444/132224559-b80db3ec-586e-4eb6-bb49-cc9a6feed533.png)

**Comment by sirskunkalot** [comment]
That's strange. Which Jötunn version do you use? Is it just the GUI?

**Comment by Dominowood371** [comment]
[Info   :    Jotunn] Jötunn v2.2.7 loaded successfully

**Comment by sirskunkalot** [comment]
*$!"&&§$% - found the bug in jötunn :) The event gets fired too early

**Comment by sirskunkalot** [comment]
Will be fixed with PlanBuild 0.5.2 and Jötunn 2.2.8
