### ISSUE TITLE
Blueprint Rune now responding to Gizmo build axis mod

### ISSUE THREAD

**Issue by AMurtagh** [sirskunkalot/PlanBuild#50]
Evening,

I use PlanBuild extensively and love it; thank you for such a great cross-section of tools.

I primarily use it for terrain editing currently but am about to start into the blueprint use soon. I also use Gizmo to enable me to rotate build pieces through all three axis, or rather more specifically I use https://valheim.thunderstore.io/package/Tyrenheim/M3TO_Gizmo_Reloaded/1.1.8/

Up until a couple of days ago, the two mods worked perfectly together. There has been no update to Gizmo, though there has been an update to PlanBuild and a number of updates to Jotunn.

As of a couple of days ago, the use of the Blueprint Rune terrain editing function now shows the three axis rotational indicator for Gizmo where it never did previously, and as a result the functionality of your mod is greatly impacted; for example when using the terrain tool and holding ALT and scrolling my mouse wheel; where previously this would have raised and lowered the altitude of my terrain editing cursor; now the cursor rotates on a new axis and doesn't change altitude.

Gizmo has a "tools to ignore" function, and I've searched /spawn for "Blueprint" and found "BlueprintRune" in the spawn list but adding this to the ignored tools changes nothing.

Has anything changed in the last couple of days that causes the tool to respond differently? Has it been tested alongside the M3TO reload of Gizmo or any other Gizmo alternative? Can you offer any potential advice on how to successfully exclude the tool from Gizmo if so?

Any help or insight very much appreciated, and happy to assist in any way if I can.

**Comment by AMurtagh** [comment]
Obviously not a robust long term fix, but if I downgrade PlanBuild to 0.10.2 the behaviour immediately reverts to what I expect and experienced historically, even with all other mods on their most recent current versions. The Gizmo axis indicators do not appear, instead just having a yellow centrepoint indicator, and the tool behaves exactly as before. If I re-upgrade to 0.10.3 the new behaviour re-exerts itself and it immediately becomes impossible to effectively use PlanBuild's terrain editing features in conjunction with Gizmo.

**Comment by sirskunkalot** [comment]
Hey, Gizmo Reloaded did not work properly anyway since the last update of Valheim. I finally got around to shift the compat to ComfyGizmo, which is 100% compatible with the current Valheim version. That meant to ditch the Gizmo Reloaded compat, though. Replace Gizmo Reloaded with this and you will be fine: https://github.com/redseiko/ValheimMods/releases/tag/ComfyGizmo-v1.3.0
