### ISSUE TITLE
Bugged Center point marker left over since update. Causing area to crash. 

### ISSUE THREAD

**Issue by Nunapplicable** [sirskunkalot/PlanBuild#51]
I can't delete this center point marker! Why has it stayed there? Why is it crashing my game and how can I delete it without reversing hours of work? Problem started after recent plan build update. 

![image](https://user-images.githubusercontent.com/110624692/182905742-16471ba5-f290-437e-b30c-008c4b294f95.png)
![image](https://user-images.githubusercontent.com/110624692/182905796-444cb3ec-bc4b-401d-a3f7-bfc22af50a93.png)

**Comment by sirskunkalot** [comment]
Hey, can you check if that fixes it? 
[PlanBuild.zip](https://github.com/sirskunkalot/PlanBuild/files/9261935/PlanBuild.zip)

**Comment by Nunapplicable** [comment]
> Hey, can you check if that fixes it? [PlanBuild.zip](https://github.com/sirskunkalot/PlanBuild/files/9261935/PlanBuild.zip)

That has resolved the issue! Thank you for that.

**Comment by sirskunkalot** [comment]
Thanks for testing, going to release a fixed version soon
