### ISSUE TITLE
zoom, rotate, build camera do not work with 0.10.5

### ISSUE THREAD

**Issue by ShadowTox** [sirskunkalot/PlanBuild#52]
the mouse wheel scroll zoom, doesn't work correctly, and with any of the CTRL, ALT, SHIFT combinations nothing works as it should.  it basically only partially rotates the blueprint model trying to be place, but that does not even work consistently.  also when trying to figure out a pattern in how it was working i managed to zoom up so high i broke the build camera!  the build camera was zoomed what seemed about 30,000 feet above ground (lol), and then NONE of the mousewheel, CTRL, ALT, SHIFT combinations did anything.  the camera was permamently disconnected from the body.  i killed myself...no change.  i logged out, still camera was in space.  the only way to get it back normal was to remove the mode completely.  definitlely not usable in this state

**Comment by ShadowTox** [comment]
I removed the mod and only then did the camera reset to normal.  i couldn't determine a pattern how it was NOT working because it wasn't functioning anyway close to a usable manner.

**Comment by sirskunkalot** [comment]
"definitlely not usable in this state" - i agree with you there, but its definitely not PlanBuild that is causing this. Hundreds of other mod users don't have that problem. Probably another mod is interfering with it. You should check your log output and see if there are any errors in it.

**Comment by sirskunkalot** [comment]
closing this, no reply
