### ISSUE TITLE
Issue with Direct build

### ISSUE THREAD

**Issue by aeger** [sirskunkalot/PlanBuild#53]
I'm an admin on my server with devcommands enabled. Holding LCTRL does not direct build blueprints. I'm unable to direct build on a local game either. 

I've disabled every mod except what is needed to run PlanBuild. Only thing I can think of is one of these Jotuun updates is causing the problem. I've done it successfully in the past.

**Comment by sirskunkalot** [comment]
Probably an incompatibility or double bind of LCTRL with another mod? Or did you rebind the key to something else?

**Comment by aeger** [comment]
You were right, it was the key bind in MinimalUI causing the problem. I appreciate your time and sorry for pestering you.

**Comment by aeger** [comment]
You were right, it was the key bind in MinimalUI causing the problem. I appreciate your time and sorry for pestering you.
