### ISSUE TITLE
Build Menu needs a Scroll Bar

### ISSUE THREAD

**Issue by gstrange42** [sirskunkalot/PlanBuild#54]
I have run into the problem that once a few mods are installed, items disappear from the bottom of the build menu. Is it possible to have a scroll bar or a way to split categories into Misc 1, Misc 2 etc?

**Comment by sirskunkalot** [comment]
There are mods out there which enable scrolling for the build menu. Pageable Build Hud for example. Not sure if that still works, though. I dont want to mess with that in PlanBuild directly because a dedicated mod also works on other tools and not just PlanBuild.

**Comment by gstrange42** [comment]
I get where you're coming from, most of the ones I have found are very glitchy. I'll give Pageable Build Hud a try of this the one I'm using messes up again.
