### ISSUE TITLE
Center point marker - Terrian modificator : Mouse1 description

### ISSUE THREAD

**Issue by An9e** [sirskunkalot/PlanBuild#62]
![image](https://user-images.githubusercontent.com/117473680/214136444-1b84f330-19af-49ed-a88a-d72d33435d94.png)
![image](https://user-images.githubusercontent.com/117473680/214136518-feaccb29-1321-4b5a-bb2c-00f8863d0b4b.png)

Center point marker : Mouse1 - Terrian modificator: Mouse1

Change of description

**Comment by sirskunkalot** [comment]
thanks, fixed in the latest version
