### ISSUE TITLE
[Warning:PlanBuild.Plans.PlanDB] Warning for mod developers

### ISSUE THREAD

**Issue by mjtroyer** [sirskunkalot/PlanBuild#65]
Seen in console on startup:

[Warning:PlanBuild.Plans.PlanDB] Warning for mod developers:
Multiple pieces with the same m_name but different resourcerequirements, this will cause issues with Player.m_knownRecipes!
Piece.m_name: $tool_cart
 Requirements:$item_wood:20, $item_bronzenails:10
 Pieces: Cart
 
 Requirements:$item_bronzenails:60, $item_finewood:40
 Pieces: rae_HorseCart

**Comment by sirskunkalot** [comment]
That can be ignored. Just a warning for mod devs (or iron gate in this case, i guess :)).
