### ISSUE TITLE
Blueprint wont change colour and is stuck pink

### ISSUE THREAD

**Issue by MkToasted** [sirskunkalot/PlanBuild#87]
since the Valheim update, all my blueprints are pink and wont change transparency or colour in the config UI
![Screenshot 2024-04-11 204133](https://github.com/sirskunkalot/PlanBuild/assets/88008570/1401c004-7d4c-4bf3-a42a-02ed76a79727)
![Screenshot 2024-04-11 204143](https://github.com/sirskunkalot/PlanBuild/assets/88008570/175d8290-8ca8-497a-85d4-4dd9d02398df)

**Comment by MkToasted** [comment]
![Screenshot 2024-04-11 204354](https://github.com/sirskunkalot/PlanBuild/assets/88008570/1a0f1eca-ffb9-49f4-91f7-8f924deb2c9a)

**Comment by wilroboly** [comment]
I've noticed this also today. I can affect the color changes in my UI config manager, but they do not reflect in the actual game. Whether done from config file mod or in-game, its stuck on pink.

**Comment by Sketaful** [comment]
This should be fixed in 1.15 according to someone, haven't had time to try it out since I got other problems with a bunch of mods atm :P

**Comment by williamroboly** [comment]
Yes. It is! Thank you very much!

**Comment by sirskunkalot** [comment]
Yeah, I fixed it in 0.15.0 ;)
