### ISSUE TITLE
MMHOOK problems

### ISSUE THREAD

**Issue by Sketaful** [sirskunkalot/PlanBuild#88]
Get this as soon as I start the game. And the window for the mod pops up in the main screen before logging into a game and at once when just starting playing. I have ValheimModding-HookGenPatcher-0.0.4

`TypeLoadException: Could not load type of field 'PlanBuild.Blueprints.BlueprintManager+<>c:<>9__9_0' (1) due to: Could not load file or assembly 'MMHOOK_assembly_valheim, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.`

**Comment by sirskunkalot** [comment]
Please follow the instructions to install HookGenPatcher carefully. Especially copying the config into BepInEx\config is crucial

**Comment by ValhallaCommunityOfficial** [comment]
I'm getting the same error in server log. mmhook is installed properly
