### ISSUE TITLE
Text for some buttons and fields not in English

### ISSUE THREAD

**Issue by Bansheedragon** [sirskunkalot/PlanBuild#93]
I got this mod from Thunderstore.
When I started using it I noticed that some of the buttons and fields are not in English, I think it may be Korean, but I'm not sure

![20240719122146_1 - Copy](https://github.com/user-attachments/assets/512ca05d-1f57-4fcd-b125-b25478e6702b)

This is only what I have seen so far, there could be more.
I can still use the mod, but having it in English would be appreciated if someone would be so kind as to take care of this.

**Comment by Bansheedragon** [comment]
Issue seems to have fixed itself, no idea what happened

**Comment by paulosincos** [comment]
I faced the same issue...

I managed to solve by removing all generated configuration files related to PlanBuild and restarting the game.
