### ISSUE TITLE
New Valheim update brought an issue to PlanBuild with it

### ISSUE THREAD

**Issue by cCaptainn** [sirskunkalot/PlanBuild#96]
[LogOutput.log](https://github.com/user-attachments/files/16759447/LogOutput.log)

**Comment by joshschools** [comment]
![image](https://github.com/user-attachments/assets/c5dc828f-268f-414f-bfed-da586470012f)

**Comment by Braehawk** [comment]
The in-game result of this for me was that upon logging in, the blueprints tab was completely gone.  The tools tab and everything that comes with it was there, but the blueprints tab was completely missing.  I was able to solve this by building something quick, small and simple and creating a blueprint out of it.  That actually made my blueprints tab, and all my blueprints show back up. So far I haven't seen any other issues.

**Comment by tobymaxgames** [comment]
having the same problems. also selecting objects for a blueprint makes them stay highlighted even if you cancel the blueprint or remove them from the selection

**Comment by BETLOG** [comment]
+1
- selection by click and radius is totally fubar
- blueprints not showing but physically present (as above)
- completely unuseable for saving a plan

**Comment by caligirl0013** [comment]
+1
same issues as above

**Comment by Tankdoz** [comment]
+1

**Comment by algo7** [comment]
> having the same problems. also selecting objects for a blueprint makes them stay highlighted even if you cancel the blueprint or remove them from the selection

Yep. Facing the same issue here. Select and unselect work but the graphic doesn't change and remain highlighted in green.

**Comment by Acurtis03** [comment]
for everyone having the issue of the pieces staying green when they save a blue print, i found that if you just fly far enough away to de-render the build, when flying back to the build the pieces are no longer green!

**Comment by BETLOG** [comment]
...2 weeks later...
Is there no update or comment from maintainer yet?
valheim discord said something about 'holidays... back next week' but that was a week ago iirc.

**Comment by joshschools** [comment]
There is a temp plugin posted on thunderstore under a different dev. You can use that until this main one is updated. I haven’t noticed any regressions on my dedicated server

**Comment by sirskunkalot** [comment]
fixed in 0.17.0
